config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "departmentals#index"
  resources :departmentals do
    resources :items
  end

  scope "items/:item_id", as: "item" do
    resources :comments, only: [:new, :create, :show]
  end
  scope "items/:item_id", as: "item" do
    resources :ratings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/departmental.rb
class Departmental < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :departmental
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy

  end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :item

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item
  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create 
    @comment = @item.comments.new(comment_params)
    if @comment.save
      redirect_to departmental_item_path(@item.departmental_id, @item)
    else
      render :new
    end
  end

  private

    def set_item
      @item = Item.find(params[:item_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end

end

app/controllers/departmentals_controller.rb
class DepartmentalsController < ApplicationController
  before_action :set_departmental, only: [:show, :edit, :update, :destroy]
  def index
    @departmentals = Departmental.all
  end

  def new
    @departmental = Departmental.new
    render partial: "form"
  end
  def create
    @departmental = Departmental.new(departmental_params)
    if @departmental.save
      redirect_to departmentals_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    render partial: "form"
  end

  def update
    if @departmental.update(departmental_params)
      redirect_to @departmental
    else
      render :edit
    end
  end

  def destroy
    @departmental.destroy
    redirect_to departmentals_path
  end

  private
  
  def set_departmental
    @departmental = Departmental.find(params[:id])
  end
  def departmental_params
    params.require(:departmental).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_departmental
  before_action :set_items, except: [:new, :create, :index]
  def index
    @items = @departmental.items
  end

  def show
    
  end

  def new
    @item = @departmental.items.new
    render partial: "form"
  end

  def create
    @item = @departmental.items.new(item_params)
    if @item.save
      redirect_to departmental_item_path(@departmental.id, @item)
    else
      render :new
    end
  end
  
  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to departmental_item_path(@departmental.id, @item.id)
    else
      render :edit
    end

  end

  def destroy
    @item.destroy
    redirect_to departmental_items_path

  end
  private 
  def set_departmental
    @departmental = Departmental.find(params[:departmental_id])
  end

  def set_items
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_item
  
  def new
    @rating = Rating.new
  end

  def create
    @rating = @item.ratings.new(rating_params)
    if @rating.save
      redirect_to departmental_item_path(@item.departmental_id, @item)
    else
      render :new
    end
  end
  private

    def set_item
      @item = Item.find(params[:item_id])
    end

    def rating_params
      params.require(:rating).permit(:rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departmentals_helper.rb
module DepartmentalsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></strong></p>
</hr>

app/views/comments/new.html.erb
<h1>Add A comment</h1>
<%= form_for [@item, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave Blank To Remain Anonymous' %>
  <br />
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/departmentals/_form.html.erb
<h1><%= @departmental.id ? 'Edit Department' : 'Create Department' %></h1>
<hr />
<%= form_for @departmental do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departmentals/edit.html.erb
<h1>Departmentals#edit</h1>
<p>Find me in app/views/departmentals/edit.html.erb</p>

app/views/departmentals/index.html.erb
<h1>List Of Departments</h1>
<%= link_to 'Create New Department', new_departmental_path %>
<ul>
  <% @departmentals.each do |dept| %>
    <li><%= link_to dept.name, dept %></li>
  <% end %>
</ul>

app/views/departmentals/new.html.erb
<h1>Departmentals#new</h1>
<p>Find me in app/views/departmentals/new.html.erb</p>

app/views/departmentals/show.html.erb
<h1><%= @departmental.name %></h1>
<hr />
<p>What would you like to do?</p>
  <%= link_to 'View Items', departmental_items_path(@departmental) %>
<br />
<%= link_to 'Edit', edit_departmental_path(@departmental) %>
<br />
<%= link_to 'Delete', @departmental, method: :delete %>
<br />
<%= link_to 'Back', departmentals_path %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit' : 'Create' %></h1>
<hr />
<%= form_for [@departmental, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.number_field :price, required: true, :step => 0.01 %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>List Of Items</h1>
<%= link_to 'Add New Item', new_departmental_item_path(@departmental) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@departmental, item] %></li>
  <% end %>
</ul>
<%= link_to 'Back', departmental_path(@departmental.id)%>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @departmental.name %></h1>




<h4><%= @item.name %></h4>
<p>$<%= @item.price %></p>
<%= link_to 'Edit Item', edit_departmental_item_path([@departmental, @item]) %>

<%= link_to 'Delete Item', [@departmental, @item], method: :delete %>
<%= link_to 'Back To Items', departmental_items_path(@departmental) %>
<%= link_to 'Add Comment', new_item_comment_path(@item) %>
<%= link_to 'Add Rating', new_item_rating_path(@item) %>
<hr />
<h2>Ratings</h2>
<%= @item.ratings.average(:rate) %> 
<hr />
<h2>Comments</h2>
<% @item.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
<% end %> 


<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Department</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/new.html.erb
<h1>Add a Rating</h1>
<%= form_for [@item, @rating] do |f| %>
  
  <%= f.label :rating %>
  <%= f.number_field :rate, :step => 0.01 %>
  <br />
  <%= f.submit %>
<% end %>